import 'angular';
import 'angular-resource';
import 'angular-route';
import 'todomvc-app-css/index.css';
import './app';
import './controllers/todo-ctrl';
import './services/todo-storage';
import './directives/todo-escape';
import './directives/todo-focus';