import 'angular';
import 'angular-resource';
import 'angular-route';
import 'todomvc-app-css/index.css';
import './app';
import './controllers/todoCtrl';
import './services/todoStorage';
import './directives/todoEscape';
import './directives/todoFocus';