name: Node.js CI

on:
  push:
    branches: 
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x, 16.x, 17.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run lint --workspaces --if-present
      - run: npm run build --workspaces --if-present
      - run: npm run test --workspaces --if-present

  publish:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@rollup-extras'
      - run: npm install
      - run: npm run build --workspaces --if-present
      - run: npm run semantic-release --workspaces --if-present
        env:
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}