name: Node.js CI

on:
  push:
    branches: 
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta

jobs:

  snyk:

    runs-on: ubuntu-latest

    if: ${{ contains(github.event.workflow_run.head_commit.message, '[Snyk]') }}
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@rollup-extras'
          cache: 'pnpm'
      - run: pnpm install
      - run:
          "git commit -a -m \"chore: update lock\""
      - run: git push

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x]

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile --prefer-offline --reporter=append-only
      - run: pnpm run lint
      - run: pnpm run build
      - run: pnpm test

  publish:

    needs: build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@rollup-extras'
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile --prefer-offline --reporter=append-only
      - run: pnpm run build
      - name: create and publish versions
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: "chore: update versions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}