name: Node.js CI

on:
  push:
    branches: 
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta
  pull_request:
    branches:
      - main
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x.x'
      - '[0-9]+.x'
      - next
      - next-major
      - alpha
      - beta

jobs:
  pipeline:
    with:
      scope: '@rollup-extras'
    uses: kshutkin/pipeline/.github/workflows/main.yml@main
    secrets: inherit